### PR TITLE
Update dependencies jsonpointer

### PR DESCRIPTION
**Pull request by NewtCobell**
Updating `eslint` will allow us to upgrade to a non-vulnerable version of `jsonpointer` per [this security advisory](https://github.com/Rhumbix/rmbx_django/security/dependabot/30)

### CODE REVIEW

**Review by jonstine — APPROVED** [review]
sure!

**Review by FredLavoie — APPROVED** [review]
Wow, eslint v1 -> v8, huge jump!
LGTM

**Comment by NewtCobell** [comment]
latest version of `eslint` is still using a non-secure version of `ajv`, but I think we should probably at least get `jsonpointer` patched.

**Comment by FredLavoie** [comment]
Yep, sounds good to me. That `ajv` security vulnerability looks pretty gnarly.

**Pull request merged**
